beneficiaries/urls.py
from django.urls import path


from beneficiaries.views import beneficiary_list, beneficiary_details, beneficiary_form, beneficiary_autoform,beneficiary_edit, beneficiary_delete



#  NÃO APAGAR FIX PARA: BRUNO 
# from beneficiaries.views import beneficiary_list, beneficiary_details,, beneficiary_form, beneficiary_autoform




app_name = 'beneficiaries'

urlpatterns = [
    path('list/',beneficiary_list, name='Beneficiarios'),
    path('<int:pk>/',beneficiary_details, name='detalhes_beneficiarios'),
    path('delete/<int:pk>/',beneficiary_delete, name='deletar_beneficiarios'),
    path('register/', beneficiary_form, name='form_beneficiarios'),
    path('autoregister/', beneficiary_autoform, name='autoform_beneficiarios'),
    path('<int:pk>/edit/', beneficiary_edit, name='editar_beneficiario'),
    


   

]

beneficiaries/models.py
from django.db import models


class Beneficiary(models.Model):
    
    class Status(models.TextChoices):
        ACTIVE = "active", "Ativo"
        PENDING = "pending", "Pendente"
        SUSPENDED = "suspended", "Suspenso"
    

  
    class CivilStatus(models.TextChoices):
        SINGLE = "single", "Solteiro(a)"
        MARRIED = "married", "Casado(a)"
        DIVORCED = "divorced", "Divorciado(a)"
        SEPARATED = "separated", "Separado(a)"
        WIDOWED = "widowed", "Viúvo(a)"



    class Education(models.TextChoices):
        NO_FORMAL_EDUCATION = "no_formal_education", "Sem instrução formal"
        BASIC_LITERACY = "basic_literacy", "Alfabetizado (sem escolarização formal)"
        ELEMENTARY_INCOMPLETE = "elementary_incomplete", "Ensino Fundamental incompleto"
        ELEMENTARY_COMPLETE = "elementary_complete", "Ensino Fundamental completo"
        HIGH_SCHOOL_INCOMPLETE = "high_school_incomplete", "Ensino Médio incompleto"
        HIGH_SCHOOL_COMPLETE = "high_school_complete", "Ensino Médio completo"
        TECHNICAL = "technical", "Ensino Técnico (nível médio)"
        UNDERGRADUATE_INCOMPLETE = "undergraduate_incomplete", "Ensino Superior incompleto"
        UNDERGRADUATE_COMPLETE = "undergraduate_complete", "Ensino Superior completo"
        SPECIALIZATION = "specialization", "Pós-graduação (Especialização / MBA)"
        MASTERS = "masters", "Mestrado"
        DOCTORATE = "doctorate", "Doutorado"
        POSTDOCTORATE = "postdoctorate", "Pós-Doutorado"

    class ColorRace(models.TextChoices):
        BRANCA = "white", "Branca"
        PRETA = "black", "Preta"
        PARDA = "brown", "Parda"
        AMARELA = "asian", "Amarela"
        INDIGENA = "indigenous", "Indígena"



   
    class UF(models.TextChoices):
        AC = "AC", "Acre"
        AL = "AL", "Alagoas"
        AM = "AM", "Amazonas"
        AP = "AP", "Amapá"
        BA = "BA", "Bahia"
        CE = "CE", "Ceará"
        DF = "DF", "Distrito Federal"
        ES = "ES", "Espírito Santo"
        GO = "GO", "Goiás"
        MA = "MA", "Maranhão"
        MT = "MT", "Mato Grosso"
        MS = "MS", "Mato Grosso do Sul"
        MG = "MG", "Minas Gerais"
        PA = "PA", "Pará"
        PB = "PB", "Paraíba"
        PE = "PE", "Pernambuco"
        PI = "PI", "Piauí"
        PR = "PR", "Paraná"
        RJ = "RJ", "Rio de Janeiro"
        RN = "RN", "Rio Grande do Norte"
        RS = "RS", "Rio Grande do Sul"
        RO = "RO", "Rondônia"
        RR = "RR", "Roraima"
        SC = "SC", "Santa Catarina"
        SE = "SE", "Sergipe"
        SP = "SP", "São Paulo"
        TO = "TO", "Tocantins"

    id_beneficiary = models.AutoField(primary_key=True)
    beneficiary_name = models.CharField(max_length=200,verbose_name="Nome Completo")
    birth_date = models.DateField(verbose_name="Data de nascimento")
    cpf = models.CharField(max_length=14,unique=True, blank=False, null=False,)
    zip_code = models.CharField(max_length=9,blank=False,null=False,verbose_name="CEP")
    street = models.CharField(max_length=200, blank=False, null=False, verbose_name="Rua")
    address_number = models.IntegerField(blank=False,null=False,verbose_name="Número") 
    address_complement = models.CharField(max_length=50, blank=True,null=True,verbose_name="Complemento")
    neighborhood = models.CharField(max_length=100,blank=False,null=False,verbose_name="Bairro")
    community_name = models.CharField(max_length=30,blank=True,null=False,verbose_name="Nome da comunidade" ) 
    city = models.CharField(max_length=100,blank=False,null=False,verbose_name="Cidade")
    state = models.CharField(max_length=2, choices=UF.choices,blank=False, null=False,verbose_name="UF")
    phone = models.CharField(max_length=15,blank=False,null=False,verbose_name="Telefone")
    email = models.EmailField(blank=False,null=False,verbose_name="E-mail")
    education = models.CharField(max_length=50, null=False,blank=False, choices=Education.choices,default='no_formal_education', verbose_name="Escolaridade")
    occupation = models.CharField(max_length=100, verbose_name="Profissão")
    race= models.CharField(max_length=20,blank=True,null=True, choices=ColorRace.choices, verbose_name="Cor/Raça")
    civil_status = models.CharField(max_length=30, choices=CivilStatus.choices,blank=False,null=False,default='single', verbose_name="Estado Civil")
    family_income = models.DecimalField(max_digits=10,decimal_places=2, verbose_name="Renda Familiar")
    dependents_count = models.IntegerField(default=0,blank=True,null=True, verbose_name="Nº dependentes")
    household_members = models.IntegerField(blank=False,null=False,verbose_name="Nº de pessoas da Família")
    emergency_contact = models.JSONField(blank=True, null=True, verbose_name="Contatos de Emergência")
    status = models.CharField(max_length=10,choices=Status.choices, default='pending')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data do Registro")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Ultima atualização")

    projects = models.ManyToManyField('projects.Project', through='projects.Enrollment')


    

    def __str__(self):
        return self.beneficiary_name
    
    class Meta:
        verbose_name = 'Beneficiário'
        verbose_name_plural = 'Beneficiários'

beneficiaries/templates/beneficiaries-details.html
{% extends 'base.html' %}
{% block title %}{{ beneficiary.nome }}{% endblock %}

 {% block extra_head %}
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
    
 
 {% endblock %}

 {% block content %}
 
<section class="w-full mt-20">
    <div class="mb-8">
        <h2 class="text-3xl font-bold text-gray-800 ">Detalhes do Beneficiário</h2>
        <p class="mt-1 text-sm text-gray-600 ">Vizualize e gerencia informações do beneficiário</p>
    </div>
    <div class="rounded-lg border border-gray-200  bg-white  shadow-sm">
        <div class="p-6">
            <h3 class="text-lg font-semibold text-gray-800  mb-4">Infomação Pessoal</h3>
            <dl class="grid grid-cols-3 grid-rows-6 gap-x-4 gap-y-6 ">
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Nome completo</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.beneficiary_name }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Data do Registro</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.created_at }}</dd>
                </div>
                 <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Rua</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.street }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">CPF</dt>
                    <dd class="mt-1 text-sm text-gray-900 0">{{ beneficiary.cpf }}</dd>
                </div>                
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Status</dt>
                    <dd
                        class="mt-1 inline-flex items-center rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800 ">{{ beneficiary.status }}</dd>
                </div>
                 <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Nº Casa</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.address_number }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Email</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.email }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Tamanho da Família</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.household_members }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Complemento</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.address_complement }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Telefone</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.phone }}</dd>
                </div>
                  <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Nº de Dependentes</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.dependents_count }}</dd>
                </div>
                 <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">UF</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.state }}</dd>
                </div>   
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Data de Nascimento</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.birth_date }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Renda Familiar</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">R$: {{ beneficiary.family_income }}</dd>
                </div>
                 <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Cidade</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.city }}</dd>
                </div> 
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Profissão</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.occupation }}</dd>
                </div>
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">CEP</dt>
                    <dd class="mt-1 text-sm text-gray-900 0">{{ beneficiary.zip_code }}</dd>
                </div>   
                <div class="sm:col-span-1">
                    <dt class="text-sm font-medium text-gray-500 ">Bairro</dt>
                    <dd class="mt-1 text-sm text-gray-900 ">{{ beneficiary.neighborhood }}</dd>
                </div>  
                   
            </dl>
        </div>
        <div class="flex flex-col gap-4 border-t border-gray-200  bg-primary  p-6 sm:flex-row sm:justify-between sm:items-center">
            <div class="flex gap-3">
                <button class="inline-flex items-center justify-center rounded   text-sm font-medium bg-blue-button/20 text-blue-button hover:bg-blue-button/30 cursor-pointer ">
                    <a class=" w-full h-full px-4 py-2" href="{% url 'beneficiaries:editar_beneficiario' beneficiary.id_beneficiary %}">
                        Editar Beneficiário
                    </a>
                </button>
                <button class="inline-flex items-center justify-center rounded bg-red-100 px-4 py-2 text-sm font-medium text-red-600  hover:bg-red-200 cursor-pointer " onclick=" deletar(`{{beneficiary.id_beneficiary}}`) ">
                    Deletar Beneficiário
                </button>
            </div>
            <button class="inline-flex items-center justify-center rounded bg-blue-button px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-button/90 cursor-pointer" onclick="donation_register_send('{{beneficiary.id_beneficiary}}') ">
                Registrar Doação
            </button>
        </div>
         <!-- {% if messages %}
            {% for message in messages %}
        <div class="w-full pl-6 text-red-600 font-medium alert alert-{{ message.tags }} self-center mx-auto">
            <span>{{ message }}</span>
        </div>
            {% endfor %}
         {% endif %}  -->
    </div>
</section>
 
 
 {% endblock %}

 {% block extra_js %}
 <script>
    const deletar = async(id)=>{

        const confirmacao = confirm(`Deseja mesmo excluir {{beneficiary.beneficiary_name}}`);

        if(!confirmacao){
            return ;
        }
    

        await fetch(`/beneficiaries/delete/${id}/`,{
        method : 'POST',
        headers :{

            'X-CSRFToken': '{{ csrf_token }}',
            'Content-Type': 'application/json',
        }
        
        })
        window.location.replace("{% url 'beneficiaries:Beneficiarios'  %}");
    }

    const donation_register_send = async(id)=>{
        const confirmation = confirm('Deseja registrar uma doação para {{ beneficiary.beneficiary_name }} ?');

        if(!confirmation){
            return ;

        }

        try {
            const response = await fetch(`/donations/register/${id}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json',
                }
            });

            const json_dataResponse = await response.json();

            if(json_dataResponse.success) {
                alert(json_dataResponse.message);
                window.location.reload();
            } else {
                alert(json_dataResponse.message);
            }
        } catch(error) {
        alert('Erro ao processar a requisição.');
        console.error('Erro:', error);
        }






    }
    


 </script>
  
 
 {% endblock %}

beneficiaries/templates/beneficiaries-list.html
{% extends 'base.html' %}
{% block title %}{{ Beneficiários }}{% endblock %}


 {% block extra_head %}
    
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />  
 
 {% endblock %}

{% block content %}
    <section class="w-full mt-20">
        <div class="mb-8 flex items-center justify-between">
            <div>
                <h2 class="text-3xl font-bold text-zinc-900 ">
                    Gestão de Beneficiários
                </h2>
                <p class="text-zinc-600 ">
                    Liste, pesquise, adicione, edite e remova beneficiários.
                </p>
            </div>
            <button
                class="rounded-lg bg-blue-button px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-blue-button/90 focus:outline-none focus:ring-4 focus:ring-blue-button/50">
               <a href="{% url 'beneficiaries:form_beneficiarios' %}"> Cadastrar Novo Beneficiário</a>
            </button>
        </div>

        {% if beneficiaries %}

        <div class="rounded-lg border border-zinc-200 bg-white shadow-sm ">
            <div class="flex items-center justify-between border-b border-zinc-200 p-4 ">
                <div class="relative w-full max-w-md">
                    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                        <span class="material-symbols-outlined text-zinc-400">search</span>
                    </div>
                    <input
                        class="form-input w-full rounded-lg border-zinc-300 bg-primary py-2 pl-10 pr-4 text-zinc-900 placeholder-zinc-400 focus:border-blue-button focus:ring-blue-button "
                        id="search" placeholder="Buscar por nome ou CPF" type="text" />
                </div>

            </div>
         
            <div class="overflow-x-auto">
                <table class="w-full text-left text-sm text-zinc-500 ">
                    <thead class="bg-zinc-50 text-xs uppercase text-zinc-700 ">
                        <tr>
                            <th class="px-6 py-3" scope="col">Nome</th>
                            <th class="px-6 py-3" scope="col">CPF</th>
                            <th class="px-6 py-3" scope="col">Telefone</th>
                            <th class="px-6 py-3" scope="col">Status</th>
                            <th class="px-6 py-3 text-center" scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for beneficiary in beneficiaries %}
                        <tr class="border-b border-border-light bg-white hover:bg-zinc-50 ">
                            <th class="whitespace-nowrap px-6 py-4 font-medium text-zinc-900 " scope="row">
                                <a href="{% url 'beneficiaries:detalhes_beneficiarios' beneficiary.id_beneficiary %}">{{ beneficiary.beneficiary_name }}</a>

                            </th>
                            <td class="px-6 py-4">{{ beneficiary.cpf }}</td>
                            <td class="px-6 py-4">{{ beneficiary.phone }}</td>
                            <td class="px-6 py-4">
                                <span
                                    class="inline-flex items-center rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800 ">Ativo</span>
                            </td>
                            <td class="px-6 py-4 text-center">
                                <button
                                    class="rounded-md bg-blue-button/25 px-3 py-1.5 text-sm font-medium text-blue-buttonlight hover:bg-zinc-200 ">
                                    <a href="{% url 'beneficiaries:editar_beneficiario' beneficiary.id_beneficiary %}">Editar</button></a>
                                <button
                                    class="ml-2 rounded-md bg-red-100 px-3 py-1.5 text-sm font-medium text-red-700 hover:bg-red-200 " onclick="deletar('{{ beneficiary.id_beneficiary }}')">Excluir</button>
                            </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
           
            
        </div>
        {% else %}
         <div class="alert alert-info">
            <p>Nenhum beneficiário cadastrado ainda.</p>
        </div>
        {%endif%}
    </section>
    {% endblock %}

    {% block extra_js %}
    <script>
        const searchInput = document.getElementById('search');
        searchInput.addEventListener('input', function() {
            const filter = searchInput.value.toLowerCase();
            const rows = document.querySelectorAll('tbody tr');

            rows.forEach(row => {
                const name = row.querySelector('th').textContent.toLowerCase();
                const cpf = row.querySelectorAll('td')[0].textContent.toLowerCase();

                if (name.includes(filter) || cpf.includes(filter)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });

        const deletar = async (id) => {
            const confirmacao = confirm("Tem certeza que deseja excluir este beneficiário?");
            if (!confirmacao) {
                return;
            }

            // enviar o nome do beneficiário para o backend para exclusão
            await fetch(`/beneficiaries/delete/${id}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json',
                },
            })
            // Reload na página após exclusão para atualizar a lista
            window.location.reload();
        }

    </script>
    {% endblock %}

beneficiaries/templates/edit-form.html
{% extends 'base.html' %}
{% block title %}{{ 'Editar Beneficiário' }}{% endblock %}


{% block content %}

<section class="container w-[63%]  mt-20 py-12 px-12 px-6 lg:px-8 rounded-xl shadow-lg border border-border-light bg-secondary">
                <div class="mb-8 text-center">
                    <h1 class="text-3xl font-bold text-black ">Editar Beneficiário</h1>
                    <p class="mt-1 text-slate-600 "> Altere os campos abaixo para editar o beneficiário no sistema.</p>
                </div>
                <form method="POST" action="{% url 'beneficiaries:editar_beneficiario' beneficiary.id_beneficiary %}" class="space-y-6">
                    
                    {% csrf_token %}

                    <div class="grid grid-cols-2 gap-y-6 gap-x-4 ">
                        <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="full-name">Nome completo</label>
                            {{form.beneficiary_name}}
                        </div>
                        <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="cpf">CPF</label>
                           {{form.cpf}}
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-black " for="dob">Data
                                de nascimento</label>
                            <input type="date" name="birth_date" class="mt-1 placeholder-subtitle block w-full rounded-lg border border-border-light bg-primary  placeholder-gray-400 focus:border-blue-500 focus:ring focus:ring-blue-200 text-gray-700 p-2 shadow-sm" required="" id="id_birth_date" value="{% if beneficiary.birth_date %}{{ beneficiary.birth_date|date:'Y-m-d' }}{% endif %}" >
                           
                        </div>
                        
                        <div>
                            <label class="block text-sm font-medium text-black "
                                for="address">Cep</label>
                            {{form.zip_code}}
                        </div>
                         <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="address">Rua</label>
                            {{form.street}}
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-black "
                                for="address">Número</label>
                            {{form.address_number}}
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-black "
                                for="address">Complemento</label>
                            {{form.address_complement}}
                        </div>
                         <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="address">Bairro</label>
                            {{form.neighborhood}}
                        </div>
                         <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="address">Cidade</label>
                            {{form.city}}
                        </div>
                         <div>
                            <label class="block text-sm font-medium text-black "
                                for="address">Estado</label>
                           {{form.state}}
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-black "
                                for="phone">Telefone</label>
                            {{form.phone}}
                        </div>
                        <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="email">E-mail</label>
                           {{form.email}}
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-black "
                                for="dependents">Quantidade de dependentes</label>
                            {{form.dependents_count}}
                        </div>
                        <div class="col-span-1">
                            <label class="block text-sm font-medium text-black "
                                for="residents">Quantidade de pessoas na residência</label>
                            {{form.household_members}}
                        </div>
                        <div class="col-span-1">
                            <label class="block text-sm font-medium text-black "
                                for="family-income">Renda Familiar (R$)</label>
                           {{form.family_income}}
                        </div>
                        <div >
                            <label class="block text-sm font-medium text-black "
                                for="profession">Profissão</label>
                            {{form.occupation}}
                        </div>                       
                        <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="status">Status da inscrição</label>
                           {{form.status}}
                        </div>
                        <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="{{ form.projects.id_for_label }}">Escolha um ou mais projetos</label>
                           {{form.projects_n}}
                        </div>
                        <!-- NÃO APAGAR FIX PARA: BRUNO                     -->

                        <!-- <div class="col-span-2">
                            <label class="block text-sm font-medium text-black "
                                for="{{ form.projeto.id_for_label }}">Escolha um projeto</label>
                           {{form.projeto}}
>
                        </div> -->
                    </div>
                    <div class=" col-span-2 flex pt-4 border-t border-slate-200 ">                        

                        <input type="submit" value="Enviar inscrição"
                            class=" w-30 flex-1 rounded-lg bg-blue-button px-4 py-2 text-sm font-bold text-white shadow-sm hover:bg-blue-button/90"/>
                    </div>
                    {% if success %}
                        <p class="text-green-600 font-semibold mb-4">Cadastro de beneficiário alterado com sucesso!</p>
                    {% endif %}
                        {% if form.errors %}
                        <div class="text-red-600 font-semibold mt-4">
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            {% endfor %}
                        </div>
                        {% endif %}

                </form>
            </section>
{% endblock %}